mysite/main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('quizes/', views.quizes, name='QZ'),
    path('',views.main, name='main'),
    path('addquestion/', views.addquestion, name='AQ'),
    path('leaderboard/', views.leaderboard, name='LD'),
    path('myachivements/', views.achv, name='MA'),
    path('lg/', views.logout_view, name='LG'),
    


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('quiz/',include('quiz.urls')),
    path('main/',include('main.urls'))
]

mysite/main/models.py
from django.db import models

from accounts.models import CustomUser

class Question_types(models.Model):
    q_type = models.CharField(max_length=50,primary_key=True)




class questionforadmin(models.Model):
    question_text = models.CharField(max_length=200)
    q_type = models.CharField(max_length=200)
    correct_choice = models.CharField(max_length=200)
    incorrect_choice1 = models.CharField(max_length=200)
    incorrect_choice2 = models.CharField(max_length=200)
    incorrect_choice3 = models.CharField(max_length=200)
    who_sent = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default='')


class Image(models.Model):
    name = models.CharField(max_length=100)
    image_data = models.BinaryField()

mysite/main/forms.py
from django import forms

from .models import Question_types



class Myform(forms.Form):
    question = forms.CharField(max_length=255,label='Question', widget=forms.TextInput(attrs={'class': 'form-input question'}))
    cat = forms.ModelChoiceField(queryset=Question_types.objects.values_list('q_type',flat=True), label="Category", empty_label="None")
    correct_answer = forms.CharField(label='Correct Answer',max_length=200, widget=forms.TextInput(attrs={'class': 'form-input answer','value':True}))
    incorrect_answer1 = forms.CharField(label='Incorrect Answer1',max_length=200, widget=forms.TextInput(attrs={'class': 'form-input answer'}))
    incorrect_answer2 = forms.CharField(max_length=200,label='Incorrect Answer2', widget=forms.TextInput(attrs={'class': 'form-input answer'}))
    incorrect_answer3 = forms.CharField(max_length=200,label='Incorrect Answer3', widget=forms.TextInput(attrs={'class': 'form-input answer'}))
    







  

mysite/main/views.py
import random
from django.shortcuts import redirect, render
from accounts.models import CustomUser
from accounts.models import Achievement
from quiz.models import Question , Answered ,Choice ,QuizHistory
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from main.forms import Myform
from django.contrib.auth import logout
from .models import questionforadmin




def addquestion(request):
    if request.method == 'POST':
        form = Myform(request.POST)
        user = request.user
        if form.is_valid():
            if user.validated:
                data = form.cleaned_data
                question = data['question']
                q_type = data['cat']
                t_q = Question(question_text=question, q_type=q_type)
                t_q.save()
                choices = [[data['correct_answer'],True],[data['incorrect_answer1'],False],[data['incorrect_answer2'],False],[data['incorrect_answer3'],False]]
                random.shuffle(choices)
                for c in choices:
                    choice = Choice(question = t_q, choice_text = c[0], is_correct = c[1])
                    choice.save()
                form = Myform()
                return render(request, 'main/addquestion.html', context={'form':form})
            else:
                data = form.cleaned_data
                question = data['question']
                q_type = data['cat']
                c_c = data['correct_answer']
                ic_c1 = data['incorrect_answer1']
                ic_c2 = data['incorrect_answer2']
                ic_c3 = data['incorrect_answer3']
                q = questionforadmin(question_text = question, q_type=q_type, correct_choice = c_c,incorrect_choice1=ic_c1,incorrect_choice2=ic_c2,incorrect_choice3=ic_c3 ,who_sent = request.user)
                q.save()
                text = 'admin will see youre question and validate'
                return render(request, 'main/addquestion.html', context={'form':form,'text':text})


        
          
    else:
        form = Myform()
    return render(request, 'main/addquestion.html', context={'form':form})



def main(request):
    return render(request, 'main/main.html')


def logout_view(request):
    logout(request)
    
    return redirect(reverse('accounts:index'))




  

def quizes(request):
    if request.method == 'POST':
        q_type = request.POST['button'] 
        user = request.user
        questions_qs = Question.objects.filter(q_type=q_type)
        answered_qs = Answered.objects.filter(user=user, question__q_type=q_type)
        answered_question_ids = answered_qs.values_list('question__id', flat=True)
        remaining_question_ids = list(questions_qs.exclude(id__in=answered_question_ids).values_list('id', flat=True))
        if len(remaining_question_ids) < 1:
            done = True
            return render(request, 'main/main.html', context={'done':done})
        elif len(remaining_question_ids) < 7:
            question_ids = remaining_question_ids
        else:
            question_ids = remaining_question_ids[:7]
        return HttpResponseRedirect(reverse('quiz:quiz', args=(question_ids, q_type)))
    else:
        q_types = list(Question.objects.values_list('q_type',flat=True).distinct())
        return render(request, 'main/quiz_choice.html', context={'q_types':q_types})



def achv(request):
    ac_user = CustomUser.objects.values_list('achievements',flat=True).filter(id=request.user.id)
    achs = Achievement.objects.filter(id__in=ac_user).values_list('name', 'description')
    if len(achs) == 0:
        achs = 'you have no achievements'
    return render(request, 'main/myachivements.html',context={'a':achs})




def leaderboard(request):
    q_types = Question.objects.values_list('q_type', flat=True).distinct()
    x = []
    print(q_types)
    
    for q in q_types:
        y = []
        a = QuizHistory.objects.values_list('user_id','high_score').filter(quiz_type=q).order_by('-high_score')
        l = len(a)
        if l == 0:
            x.append((q,[('no one took quiz', 0)]))
        elif l<5:
            for i in range(l):
                y.append((CustomUser.objects.values_list('username',flat=True).get(id=a[i][0]),a[i][1]))
        else:
            for i in range(5):
                y.append((CustomUser.objects.values_list('username',flat=True).get(id=a[i][0]), a[i][1]))
        x.append((q,y))
    print(x)
    return render(request, 'main/leaderboard.html',context={'x':x})

mysite/main/templates/main/addquestion.html
{% extends 'main/main.html' %}
{% block  content%}
   
<form action="{% url 'main:AQ' %}" method="post" class='new_queestion'>
    {% csrf_token %}
    <p class='p_inform'>{{text}}</p>

     {% for field in form %}
    <div class="form-field">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
    </div>
    {% endfor %}    
    <div class='btn-container'><button type="submit" name='fomrsubmit' class='sbtbtn' >Submit</button></div>
    
</form>
 
{% endblock%}



 

mysite/main/templates/main/leaderboard.html
{% extends 'main/main.html' %}
{% block content %}


<div class='maincontainer'>
<select id="selectQuiz" >
    <option value="" selected>select type</option>
    {% for i in x %}
    <option value="{{ i.0 }}">{{ i.0 }}</option>
    {% endfor %}
</select>

<div id="tablesContainer" class='taiblecontainer' >
    {% for i in x %}
    <table id="{{ i.0 }}" class="table hidden">
        <tr class='thead'>
            <th class='th'>Name</th>
            <th class='th'>Score</th>
        </tr>
        {% for y in i.1 %}
        <tr>
            <td class='td'>{{ y.0 }}</td>
            <td class='td'>{{ y.1 }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endfor %}
</div>
</div>


{% endblock %}

mysite/main/templates/main/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="headercontainer">
        <header class="header inactive">
            <div class="menucontainer active">
            <nav class="menu">
            <a class='ripple' href="{% url 'main:MA' %}"><div class="achivements mainbtn">Achivements</div></a>
            <a class='ripple' href="{% url 'main:QZ' %}"><div class="quizes mainbtn" >Offered Quizes</div></a>
            <a class='ripple' href="{% url 'main:AQ' %}"><div class="addquestion mainbtn">Add Question</div></a>
            <a class='ripple' href="{% url 'main:LD' %}"><div class="leaderboards mainbtn">leaderboards</div></a>
            <a class='ripple' href="{% url 'main:LG' %}"><div class="logout mainbtn">Logout</div></a>
            </nav>
            </div>
            <div class="burger">
                <span></span>
            </div>
        </header>
        </div>
    <div class='content'>
    {% block content %}
    {% endblock %}
    </div>
    
  



<script src="{% static 'main/js/script.js' %}"></script>
 
</body>
</html>

mysite/main/templates/main/myachivements.html
{% extends 'main/main.html' %}

{% block content %}
<div class="achivement-container">
{% for i in a %}
<div class="achcontainer">
    <div class="ach-name"><p>{{i.0}}</p></div>
    <div class="ach desc"><p>{{i.1}}</p></div>

</div>
{% endfor %}
</div>


{% endblock%}

mysite/main/templates/main/quiz_choice.html
{%extends 'main/main.html'%}
{%block content%}
     <form method="POST" action="{% url 'main:QZ' %}" class='quizchoice'>
        <div class='quizbtncont'>
        {% csrf_token %}
        {%for q in q_types%}
        <button class="quizbutton" id="button" name="button" value="{{q}}" class='quizbutton'>{{q|upper}}</button>
        {%endfor%}
        </div>

    </form> 
        
    
    <div id="myModal" class="modal" style="display:{% if done %}block{% else %}none{% endif %}">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>You have completed the quiz</h2>
            <p>Congratulations! You have answered all the questions.</p>
        </div>
        </div>
{%endblock%}  