mysite/main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('quizes/', views.quizes, name='QZ'),
    path('',views.main, name='main'),
    path('addquestion/', views.addquestion, name='AQ'),
    path('leaderboard/', views.leaderboard, name='LD'),
    path('myachivements/', views.achv, name='MA'),
    path('lg/', views.logout_view, name='LG'),
    


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('quiz/',include('quiz.urls')),
    path('main/',include('main.urls'))
]

mysite/quiz/urls.py
from django.urls import path
from . import views
app_name = 'quiz'
urlpatterns = [
    path('<str:question_ids>/<str:q_type>/',views.quiz, name='quiz')
]

mysite/quiz/models.py
from django.db import models
import requests, random
from accounts.models import CustomUser
import html


class Question (models.Model):
    question_text = models.CharField(max_length=200)
    q_type = models.CharField(max_length=200)
    def __str__(self):
        return self.question_text
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    def __str__(self):
        return self.choice_text

class QuizHistory(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default='')
    quiz_type = models.CharField(max_length=100)
    high_score = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.username} - {self.quiz_type} - High Score: {self.high_score}"
    

class Answered(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, default='')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)


    

# def add_data_mythology():
#     for i in range(50):
#         resp = requests.get(url="https://opentdb.com/api.php?amount=47&category=20&type=multiple")
#         data = resp.json()['results']
#         for i in data:
#                 if not Question.objects.filter(question_text=i['question']).exists():
#                     x = Question(question_text = i['question'], q_type = 'mythology' )
#                     y = [(i['correct_answer'],True),(i['incorrect_answers'][0],False),(i['incorrect_answers'][1],False),(i['incorrect_answers'][2],False)]
#                     random.shuffle(y)
#                     x.save()
#                     for j in y:
#                         c = Choice(question = x, choice_text = j[0], is_correct = j[1])
#                         c.save()




    # print(x)



# def add_data_animes():
#     for _ in range(50):
#         resp = requests.get(url="https://opentdb.com/api.php?amount=50&category=31&type=multiple")
#         data = resp.json()['results']
#         for item in data:
#             question_text = html.unescape(item['question'])
            
#             if not Question.objects.filter(question_text=question_text).exists():
#                 x = Question(question_text=question_text, q_type='anime')
#                 choices = [
#                     (html.unescape(item['correct_answer']), True),
#                     (html.unescape(item['incorrect_answers'][0]), False),
#                     (html.unescape(item['incorrect_answers'][1]), False),
#                     (html.unescape(item['incorrect_answers'][2]), False)
#                 ]
#                 random.shuffle(choices)
#                 x.save()  
                
#                 for choice_text, is_correct in choices:
#                     c = Choice(question=x, choice_text=choice_text, is_correct=is_correct)
#                     c.save()





# def add_data_animes():
#     for i in range(50):
#         resp = requests.get(url="https://opentdb.com/api.php?amount=50&category=31&type=multiple")
#         data = resp.json()['results']
#         for i in data:
#                 if not Question.objects.filter(question_text=i['question']).exists():
#                     x = Question(question_text = i['question'], q_type = 'anime' )
#                     y = [(i['correct_answer'],True),(i['incorrect_answers'][0],False),(i['incorrect_answers'][1],False),(i['incorrect_answers'][2],False)]
#                     random.shuffle(y)
#                     x.save()
#                     for j in y:
#                         c = Choice(question = x, choice_text = j[0], is_correct = j[1])
#                         c.save()
    

mysite/quiz/views.py
from django.contrib.auth import logout
from django.shortcuts import render ,redirect
from django.urls import reverse
from .models import Question ,QuizHistory ,Answered
from accounts.models import Achievement

def get_question(question_ids):
    question_ids = question_ids[1:-1]
    question_ids = [int(item) for item in question_ids.split(",")]
    return question_ids

def getting_score(request,q_type,score):
    if QuizHistory.objects.filter(user=request.user, quiz_type=q_type).exists():
        h = QuizHistory.objects.get(user=request.user, quiz_type=q_type)
        if h.high_score < score:
            h.high_score = score
            h.save()
            x = f'congrats you have a new high score {score}'
        else:
            x = f'your score is {score}, your high score is: {h.high_score}'
    else:
        history = QuizHistory(user=request.user, quiz_type=q_type, high_score=score)
        history.save()
        x = QuizHistory(user=request.user, quiz_type=q_type, high_score=score)
        x = x.high_score
        x = f'your score is {score}'
    return x

def check_and_add_achievement(request,name):
    user = request.user
    user_achievements = user.achievements.all()
    has = user_achievements.filter(name=name).exists()
    if not has:
        achievement = Achievement.objects.get(name=name)
        user.achievements.add(achievement)

def check_achivements(request):
    user = request.user
    user.quizes_done +=1
    user.save()
    q_d = user.quizes_done
    if q_d == 1:
        name = 'first quiz'
        achievement = Achievement.objects.get(name=name)
        user.achievements.add(achievement)
    elif q_d == 3:
        name = 'gumbert gumbert'
        achievement = Achievement.objects.get(name=name)
        user.achievements.add(achievement)





def quiz(request, q_type, question_ids):
    template_name = 'quiz/quiz_template.html'
    if request.method == 'POST':
     
        if 'logout' in request.POST:
   
            logout(request)
            err = ''
            return redirect(reverse('accounts:index'),context={'err': err})
        elif 'timersubmit' in request.POST:
            name = 'james may'
            check_and_add_achievement(request,name)
            x = 'Time Out You Failed'
            context = {'done': True, 'x': x, 'q_type': q_type,'question_ids': question_ids}
            return render(request, template_name, context)
        elif 'SBT' in request.POST:
            score = int(request.POST.get('score'))
            x = getting_score(request, q_type=q_type,score=score)
            done = True
            answered_ids = request.POST.get('answered')
            if len(answered_ids)>0:
                ids_list = [int(num) for num in answered_ids.split(",")]
            else:
                ids_list = []
            check_achivements(request)
            if score == 7:
                name = 'monster'
                check_and_add_achievement(request,name)
            for i in ids_list:
                q = Question.objects.get(id=i)
                answered = Answered(user=request.user, question=q)
                answered.save()
            context = {'x':x,'done':done , 'q_type':q_type, 'question_ids':question_ids}
            return render(request, template_name, context)
        elif 'newquiz' or 'qq' in request.POST: 
            print('newquiz')   
            return redirect(reverse('main:QZ'))
    else:
        time = 180
        ids = get_question(question_ids)
        x = 0
        list = []
        for id in ids:
            question = Question.objects.get(q_type=q_type, id=id)
            choices = question.choice_set.all()
            list.append((x,question,choices))
            x+=1
        context = {'list': list, 'q_type': q_type,'question_ids': question_ids ,'time':time}
        return render(request, template_name, context)




  

mysite/quiz/templates/quiz/quiz_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quiz/style.css' %}">
    <title>Document</title>
</head>
<body>
    <header style="display: {% if not done %}block{% else %}none{% endif %}">
    <div class="base-container" >
        <div id="timer"></div>
        <form method="POST"action='{% url "quiz:quiz" q_type=q_type question_ids=question_ids %}' >
            {% csrf_token %}
            <button class="qq" name='qq' action='{% url "quiz:quiz" q_type=q_type question_ids=question_ids %}'>Quit</button>
        </form> 
        </div>
    </header>
    <form method="POST" 
    action='{% url "quiz:quiz" q_type=q_type question_ids=question_ids %}' 
    style="display: {% if not done %}none{% else %}block{% endif %}">
    {% csrf_token %}
    <div class="test-done" >
        <p>{{x}}</p>
        <div class="done_buttons">
            <button class="done_button"  name='newquiz'>New Quiz</button>
            <button class="done_button" name='logout'>Log Out</button>
        </div>
    </div>
    </form> 
    <div class="container", style="display: {% if not done %}block{% else %}none{% endif %}"> 
        {% for q in list %}
        <div class="questions" style="display: none;">  
            <div class="question_text">
                {{q.1.question_text}}
                <input class='q_id' type="hidden" name="qs" value="{{q.1.id}}">
            </div>
            <div class="choices">
            {% for choice in q.2 %}
            <div class="choice">
                <input type="radio" name="choice" value="{{choice.is_correct}}" class="choice_input{{q.0}}">
                <label for="choice">{{choice.choice_text}}</label>
            </div>
            {% endfor %}
            </div>
        </div>
        {% endfor %}
        
        <div class="buttons">
            <button class='button' id="submit">submit</button>
            <button class='button' id="next" disabled='disabled'>next</button>  
        </div>
    </div>
    <form method="POST" 
    action='{% url "quiz:quiz" q_type=q_type question_ids=question_ids %}' >
            {% csrf_token %}
            <input type="hidden" id='score' name="score" value="">
            <input type="hidden" id='answered' name="answered" value="">
            <input type="submit" name="SBT" id='sbt' style="display: none;">
            <input type="submit" name="timersubmit" id='timersubmit' style="display: none;">
            
    </form>
    <input type="hidden" id='time' name="time" value="{{time}}">
    
        
             

    <script> 
        
            const images = ["mysite/quiz/static/images/angels.jpg","images/egypt.jpg","images/fenix.jpg","images/greeks.jpg","images/olymp.jpg"]
            const form_submit = document.getElementById('sbt')
            const timer = document.getElementById('timer');
            const time = document.getElementById('time')
            let timeValue = time.value
            const t_b = document.getElementById('timersubmit')
            const Score = document.getElementById('score')
            const Answered = document.getElementById('answered')
            const submit = document.getElementById('submit')
            const next = document.getElementById('next');
            const f = document.querySelectorAll('.questions');
            let ids_list = []
            let i = 0 
            let score = 0
            f[i].style.display = 'block'
            next.addEventListener('click', (event) => {
          
                event.preventDefault();
                if (i < 6){
           
                f[i].style.display = 'none' ;
                i++;
                f[i].style.display = 'block'
                next.setAttribute('disabled','disabled')
                submit.removeAttribute('disabled')
                }
                else{
               
                    Score.setAttribute('value',score)
                    Answered.setAttribute('value',ids_list)
                    form_submit.click()

                }
            });
            
            submit.addEventListener('click', (event)=>{
                event.preventDefault();
                const selectedChoice = document.querySelector('input[name="choice"]:checked');
                const choices = document.querySelectorAll(`.choice_input${i}`);
                const q_id = document.querySelectorAll('.q_id');
                let v = q_id[i]
                let ids = v.value
                submit.setAttribute('disabled','disabled')
                next.removeAttribute('disabled')
                choices.forEach(choice => {
                    choice.disabled = true;
                  });

                
                if (selectedChoice.value == 'True'){
                    selectedChoice.parentElement.style.border = '1px solid green'  
                    score++ 
                    ids_list.push(ids)
                }
                else{
                    selectedChoice.parentElement.style.border = '1px solid red'
                    }
            }) 

            
             if (timeValue > 0){
                updateTimer();
            
                const timerInterval = setInterval(updateTimer, 1000);
            
            }
            function updateTimer() {
            const remainingTime = timeValue
            const newRemainingTime = remainingTime - 1;
            timeValue = newRemainingTime
            time.value = timeValue
    
            const minutes = Math.floor(newRemainingTime / 60);
            let seconds = newRemainingTime % 60;
            if (seconds < 10) {
            seconds = '0' + seconds;
            }
            timer.textContent = `${minutes}:${seconds}`;
            if (minutes < 1) {
            timer.style.color = 'red';
            } 
            if (timeValue === 0) {
                const k = document.getElementById('timersubmit')
                t_b.click();
                clearInterval(timerInterval);
            }
            }

    </script>
</body>
</html>